name: Back-end Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Check Java version
      run: java -version

    - name: Check Maven version
      run: mvn -v

    - name: Build with Maven
      run: mvn clean verify -X

    - name: Generate JaCoCo report
      run: mvn jacoco:report

    - name: Upload JaCoCo report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco
